version: "2"
services:
    db:
        image: mariadb:latest
        environment:
            - MYSQL_DATABASE=mydatabase
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - "./db:/var/lib/mysql"
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "80:80"
        links:
            - "db:db"
