version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        PGDATA: /data/postgres
    ports:
        - "5432:5432"
    volumes:
        - './data/postgres:/data/postgres'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
